import re
import time
import inspect
from pydantic import BaseModel
from abc import ABC, abstractmethod
from typing import Optional, get_type_hints, List, Dict, Any, Union, AsyncIterator, Callable


from .response import ToolResponse, ToolStatus
from .errors import ToolErrorCode

class ToolParameters(BaseModel):

    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None

class Tool(ABC):


    def __init__(self, name:str, description:str, expandable: bool = False):

        self.name = name
        self.description = description
        self.expandable = expandable
    
    @abstractmethod
    def run(self, parameters: Dict[str, Any]) -> Any:
        """运行工具"""
        pass

    @abstractmethod
    def get_parameters(self) -> List[ToolParameters]:
        """获取工具参数列表"""
        pass

    def run_with_timing(self, parameters: Dict[str, Any]) -> Dict[str, Any]:
        """运行工具并返回结果和统计信息"""
        start_time = time.time()
        
        try:
            response = self.run(parameters)
        except Exception as e:
            elapsed_ms = (time.time() - start_time) * 1000
            return
        if response.stats is None:
            response.stats = {}
        response.stats["time_ms"] = int(elapsed_ms)

        if response.status is None:
            response.context = {}
        response.context["parameters"] = parameters
        response.context["tool_name"] = self.name

        return response
    
    def get_expanded_tools(self) ->Optional[List['Tool']]:
        """get expanded tools if expandable is True"""

        if not self.expandable:
            return None
        
        tools = []
        for name, method in inspect.getmembers(self, predicate=inspect.ismethod):
            if hasattr(method, "_is_tool_action"):
                tool = AutoGeneratedTool(
                    parent = self,
                    method = method,
                    name = method._tool_name,
                    description = method._tool_description
                )
                tools.append(tool)

            return tools if tools else None
        
        def validate_parameters(self, parameters: Dict[str, Any]) -> bool:
            """validate parameters before running the tool"""
            required_params = [p for p in self.get_parameters() if p.required]
            return all(param in parameters for param in required_params)
        
        def to_dict(self) -> Dict[str, Any]:
            """serialize tool to dict for agent to understand"""
            return {
                "name": self.name,
                "description": self.description,
                "parameters": [p.dict() for p in self.get_parameters()],
            }
        
        def to_openai_schema(self) -> Dict[str,Any]:

            parameters = self.get_parameters()

            property = {}
            required = []

            for param in parameters:
                prop = {
                    "type": param.type,
                    "description": param.description,
                }

                if param.default is not None:
                    prop["description"] = f"{param.description} (default: {param.default})"

                property[param.name] = prop

                if param.required:
                    required.append(param.name)

            return {
                "type": "function",
                "function": {
                    "name": self.name,
                    "description": self.description,
                    "parameters": {
                        "type": "object",
                        "properties": property,
                        "required": required
                    }
                }
            }
        
        def __str__(self) -> str:
            return f"Tool(name={self.name})"
        
        def __repr__(self) -> str:
            return self.__str__()

class AutoGeneratedTool(Tool):

    def __init__(self, parent: Tool, method: Callable, name: str = None, description: str = None):

        self.parent = parent
        self.method = method

        if name is None:

            method_name = method.__name__.lstrip("_")
            name = f"{parent.name}_{method_name}"
        
        if description is None:
            description = self._extract_description_from_docstring()
        
        super().__init__(name=name, description=description)

        self._parameters = self._parse_parameters()
        
    def _extract_description_from_docstring(self) -> str:
        doc = inspect.getdoc(self.method)
        if not doc:
            return f"executing {self.method.__name__}"
        
        lines = doc.split('\n')
        for line in lines:
            line = line.strip()
            if line and not line.startswith('Args:') and not line.startswith('Returns:'):
                return line

        return f"执行 {self.method.__name__}"
    
    def _parse_parameters(self) -> List[ToolParameters]:
        
        sig = inspect.signature(self.method)
        type_hints = get_type_hints(self.method)
        docstring = inspect.getdoc(self.method) or ""

        param_descriptions = self._parse_param_descriptions_from_docstring(docstring)

        parameters = []
        for param_name, param in sig.parameters.items():
            if param_name == "self":
                continue

            param_type_hint = type_hints.get(param_name,str)
            param_type = self._python_type_to_tool_type(param_type_hint)

            required = param.default == inspect.Parameter.empty
            default = None if required else param.default

            description = param_descriptions.get(param_name, f"参数 {param_name}")

            parameters.append(ToolParameters(
                name=param_name,
                type=param_type,
                description=description,
                required=required,
                default=default
            ))
        
        return parameters
    
    def _parse_param_descriptions(self, docstring: str) -> Dict[str, str]:

        descriptions = {}
        args_match = re.search(r'Args:\s*\n(.*?)(?:\n\s*\n|Returns:|$)', docstring, re.DOTALL)
        if not args_match:
            return descriptions

        args_section = args_match.group(1)


        param_pattern = r'^\s*(\w+)(?:\s*\([^)]+\))?\s*:\s*(.+?)(?=^\s*\w+\s*(?:\([^)]+\))?\s*:|$)'
        matches = re.finditer(param_pattern, args_section, re.MULTILINE | re.DOTALL)

        for match in matches:
            param_name = match.group(1).strip()
            param_desc = match.group(2).strip()

            param_desc = re.sub(r'\s+', ' ', param_desc)
            self.descriptions[param_name] = param_desc
        
        return descriptions
    def _python_type_to_tool_type(self, python_type: Any) -> str:

        origin = getattr(python_type, '__origin__', None)
        if origin is not None:
            if origin is list:
                return "array"
            elif origin is dict:
                return "object"
            
        type_map = {
            str: "string",
            int: "integer",
            float: "number",
            bool: "boolean",
            list: "array",
            dict: "object",
        }

        return type_map.get(python_type, "string")
    
    def get_parameters(self) -> List[ToolParameters]:
        return self._parameters
    
    def run(self, parameters: Dict[str, Any]) -> Any:

        try:
            result = self.method(**parameters)

            if isinstance(result, ToolResponse):
                return result
            
            return ToolResponse.success(
                text=str(result), 
                data={"output": result}
            )
        
        except Exception as e:
            return ToolResponse.error(
                code=ToolErrorCode.EXECUTION_ERROR,
                message=f"方法执行失败: {str(e)}"
            )